from pathlib import Path

TRUTH=Path('hfamap/src/HFAMapRuntimeModificationTruth.m')
TRACE=Path('hfamap/src/HFAMapPatchExecutionTrace.m')
UI=Path('hfamap/src/HFAMapCyberUI.m')

s=TRUTH.read_text()
if '#import "HFAMapIL2CPPRuntimeResolver.h"' not in s:
    anchor='#import "HFAMapRuntimeModificationTruth.h"\n'
    if anchor not in s: raise SystemExit('truth import anchor missing')
    s=s.replace(anchor,anchor+'#import "HFAMapIL2CPPRuntimeResolver.h"\n',1)

addr_fn='''static NSDictionary *HFATAddressInfo(uintptr_t a){\n    if(!a)return @{};Dl_info d={0};if(!dladdr((void*)a,&d)||!d.dli_fbase||!d.dli_fname)return @{ @"address":[NSString stringWithFormat:@"0x%llX",(unsigned long long)a] };\n    return @{ @"address":[NSString stringWithFormat:@"0x%llX",(unsigned long long)a],@"image":HFATBaseName(d.dli_fname),@"rva":[NSString stringWithFormat:@"0x%llX",(unsigned long long)(a-(uintptr_t)d.dli_fbase)],@"symbol":d.dli_sname?[NSString stringWithUTF8String:d.dli_sname]:@"" };\n}\n'''
helper='''\nstatic NSDictionary *HFATIL2CPPSemantic(uintptr_t address){\n    if(!address)return @{ @"attempted":@NO,@"resolved":@NO };\n    NSDictionary *hit=HFAIL2CPPResolveNativeAddress((const void *)address);\n    NSMutableDictionary *out=[NSMutableDictionary dictionaryWithDictionary:hit?:@{}];\n    out[@"attempted"]=@YES;out[@"resolved"]=@([hit[@"resolved"] boolValue]);\n    return out;\n}\n'''
if 'HFATIL2CPPSemantic' not in s:
    if addr_fn not in s: raise SystemExit('address info anchor missing')
    s=s.replace(addr_fn,addr_fn+helper,1)

old='''if(!a||!n||!HFATRange(a,n,NO)){o[@"state"]=@"unreadable";o[@"verified"]=@NO;return o;}\n    NSData *cur=[NSData dataWithBytes:(void*)a length:n];o[@"runtimeBytes"]=HFATHexData(cur);o[@"runtimeAddress"]=[NSString stringWithFormat:@"0x%llX",(unsigned long long)a];NSString *state=@"unknown";'''
new='''if(a){NSDictionary *sem=HFATIL2CPPSemantic(a);o[@"targetIL2CPP"]=sem;NSLog(@"[V031314-IL2CPP-TARGET] mechanism=fixed-patch target=%@+%@ resolved=%u canonical=%@",image,rva,[sem[@"resolved"] boolValue]?1:0,[sem[@"canonical"] description]?:@"");}\n    if(!a||!n||!HFATRange(a,n,NO)){o[@"state"]=@"unreadable";o[@"verified"]=@NO;return o;}\n    NSData *cur=[NSData dataWithBytes:(void*)a length:n];o[@"runtimeBytes"]=HFATHexData(cur);o[@"runtimeAddress"]=[NSString stringWithFormat:@"0x%llX",(unsigned long long)a];NSString *state=@"unknown";'''
if old not in s: raise SystemExit('patch semantic anchor missing')
s=s.replace(old,new,1)

old='''if(original)o[@"originalPointer"]=HFATAddressInfo(original);if(target)o[@"targetAddress"]=HFATAddressInfo(target);if(replacement)o[@"replacementAddress"]=HFATAddressInfo(replacement);\n    NSLog(@"[V031313-HOOK-STATE]'''
new='''if(original)o[@"originalPointer"]=HFATAddressInfo(original);if(target){o[@"targetAddress"]=HFATAddressInfo(target);NSDictionary *sem=HFATIL2CPPSemantic(target);o[@"targetIL2CPP"]=sem;NSLog(@"[V031314-IL2CPP-TARGET] mechanism=runtime-hook target=%@+%@ resolved=%u canonical=%@",targetImage,targetRVA,[sem[@"resolved"] boolValue]?1:0,[sem[@"canonical"] description]?:@"");}if(replacement)o[@"replacementAddress"]=HFATAddressInfo(replacement);\n    if(original){NSDictionary *oi=HFATAddressInfo(original);NSString *oiImage=[oi[@"image"] description]?:@"";o[@"originalPointerClassification"]=[oiImage isEqualToString:targetImage]?@"target-image":([oiImage isEqualToString:menuImage]?@"menu-trampoline":@"other-image");}\n    NSLog(@"[V031313-HOOK-STATE]'''
if old not in s: raise SystemExit('hook semantic anchor missing')
s=s.replace(old,new,1)

old='''NSMutableArray *patches=[NSMutableArray array],*hooks=[NSMutableArray array],*startup=[NSMutableArray array];NSMutableSet *menuIds=[NSMutableSet set],*startupGroups=[NSMutableSet set];NSUInteger enabled=0,original=0,unknown=0,unreadable=0;'''
new='''NSMutableArray *patches=[NSMutableArray array],*hooks=[NSMutableArray array],*startup=[NSMutableArray array];NSMutableSet *menuIds=[NSMutableSet set],*startupGroups=[NSMutableSet set],*startupAppliedGroups=[NSMutableSet set],*activePatchFeatureIds=[NSMutableSet set];NSUInteger enabled=0,original=0,unknown=0,unreadable=0;'''
if old not in s: raise SystemExit('truth collection anchor missing')
s=s.replace(old,new,1)

old='''if([[e[@"ownerClass"] description] isEqual:@"startup-owned"]){[startup addObject:v];NSDictionary *oe=[e[@"ownershipEvidence"] isKindOfClass:NSDictionary.class]?e[@"ownershipEvidence"]:@{};NSString *group=[oe[@"constructorRVA"] description];if(!group.length)group=[NSString stringWithFormat:@"backend-%@",e[@"analyzerBackendId"]?:@0];[startupGroups addObject:group];}NSString *st=v[@"state"]?:@"";if([st isEqual:@"enabled"])enabled++;else if([st isEqual:@"original"])original++;else if([st isEqual:@"unreadable"])unreadable++;else unknown++;}'''
new='''if([[e[@"ownerClass"] description] isEqual:@"startup-owned"]){[startup addObject:v];NSDictionary *oe=[e[@"ownershipEvidence"] isKindOfClass:NSDictionary.class]?e[@"ownershipEvidence"]:@{};NSString *group=[oe[@"constructorRVA"] description];if(!group.length)group=[NSString stringWithFormat:@"backend-%@",e[@"analyzerBackendId"]?:@0];[startupGroups addObject:group];if([[v[@"state"] description] isEqual:@"enabled"])[startupAppliedGroups addObject:group];}NSString *st=v[@"state"]?:@"";if([st isEqual:@"enabled"]){enabled++;if(fid.length)[activePatchFeatureIds addObject:fid];}else if([st isEqual:@"original"])original++;else if([st isEqual:@"unreadable"])unreadable++;else unknown++;}'''
if old not in s: raise SystemExit('startup applied anchor missing')
s=s.replace(old,new,1)

old='''NSUInteger menuFeatureCount=menuIds.count+hooks.count,startupFeatureCount=startupGroups.count,effectiveFeatureCount=menuFeatureCount+startupFeatureCount;\n    NSDictionary *out=@{@"schema":@"com.hfa.runtime-modification-truth/v0.3.13.13",@"analysisOnly":@YES,@"menuFeatureCount":@(menuFeatureCount),@"startupFeatureCount":@(startupFeatureCount),@"startupModificationCount":@(startup.count),@"effectiveFeatureCount":@(effectiveFeatureCount),@"fixedPatchSiteCount":@(patches.count),@"runtimeHookCount":@(hooks.count),@"installedHookCount":@(installedHooks),@"enabledPatchCount":@(enabled),@"originalPatchCount":@(original),@"unknownPatchCount":@(unknown),@"unreadablePatchCount":@(unreadable),@"patches":patches,@"runtimeHooks":hooks,@"startupModifications":startup};\n    NSLog(@"[V031313-TRUTH-SUMMARY] menu=%lu startup=%lu effective=%lu patchSites=%lu hooks=%lu installedHooks=%lu enabled=%lu original=%lu unknown=%lu unreadable=%lu",(unsigned long)menuFeatureCount,(unsigned long)startupFeatureCount,(unsigned long)effectiveFeatureCount,(unsigned long)patches.count,(unsigned long)hooks.count,(unsigned long)installedHooks,(unsigned long)enabled,(unsigned long)original,(unsigned long)unknown,(unsigned long)unreadable);return out;'''
new='''NSUInteger menuFeatureCount=menuIds.count+hooks.count,startupFeatureCount=startupGroups.count,discoveredFeatureCount=menuFeatureCount+startupFeatureCount;NSUInteger startupAppliedFeatureCount=startupAppliedGroups.count,installedModificationCount=enabled+installedHooks;BOOL activeFeatureStateComplete=(hooks.count==0);NSUInteger activeFeatureCountKnown=activePatchFeatureIds.count+startupAppliedFeatureCount;\n    NSDictionary *out=@{@"schema":@"com.hfa.runtime-modification-truth/v0.3.13.14",@"analysisOnly":@YES,@"menuFeatureCount":@(menuFeatureCount),@"startupFeatureCount":@(startupFeatureCount),@"startupOwnedFeatureCount":@(startupFeatureCount),@"startupAppliedFeatureCount":@(startupAppliedFeatureCount),@"startupModificationCount":@(startup.count),@"discoveredFeatureCount":@(discoveredFeatureCount),@"effectiveFeatureCount":@(discoveredFeatureCount),@"effectiveFeatureCountDeprecated":@YES,@"installedModificationCount":@(installedModificationCount),@"activeFeatureCountKnown":@(activeFeatureCountKnown),@"activeFeatureStateComplete":@(activeFeatureStateComplete),@"fixedPatchSiteCount":@(patches.count),@"runtimeHookCount":@(hooks.count),@"installedHookCount":@(installedHooks),@"enabledPatchCount":@(enabled),@"originalPatchCount":@(original),@"unknownPatchCount":@(unknown),@"unreadablePatchCount":@(unreadable),@"il2cppRuntime":HFAIL2CPPResolverStatus(),@"patches":patches,@"runtimeHooks":hooks,@"startupModifications":startup};\n    NSLog(@"[V031314-TRUTH-SUMMARY] discovered=%lu menu=%lu startupOwned=%lu startupApplied=%lu installedMods=%lu activeKnown=%lu activeComplete=%u patchSites=%lu hooks=%lu installedHooks=%lu enabled=%lu original=%lu unknown=%lu unreadable=%lu",(unsigned long)discoveredFeatureCount,(unsigned long)menuFeatureCount,(unsigned long)startupFeatureCount,(unsigned long)startupAppliedFeatureCount,(unsigned long)installedModificationCount,(unsigned long)activeFeatureCountKnown,activeFeatureStateComplete?1:0,(unsigned long)patches.count,(unsigned long)hooks.count,(unsigned long)installedHooks,(unsigned long)enabled,(unsigned long)original,(unsigned long)unknown,(unsigned long)unreadable);return out;'''
if old not in s: raise SystemExit('truth summary/output anchor missing')
s=s.replace(old,new,1)
TRUTH.write_text(s)

# Bundle log bridge: repair literal backslash-n and emit v031314 semantic summaries.
t=TRACE.read_text()
t=t.replace('\\\\n"','\\n"')
old='''HFALog("[V031313-TRUTH-SUMMARY] menu=%u startup=%u startupMods=%u effective=%u patchSites=%u hooks=%u installedHooks=%u enabled=%u original=%u unknown=%u unreadable=%u\\n",\n               [runtimeTruth[@"menuFeatureCount"] unsignedIntValue],[runtimeTruth[@"startupFeatureCount"] unsignedIntValue],[runtimeTruth[@"startupModificationCount"] unsignedIntValue],[runtimeTruth[@"effectiveFeatureCount"] unsignedIntValue],[runtimeTruth[@"fixedPatchSiteCount"] unsignedIntValue],[runtimeTruth[@"runtimeHookCount"] unsignedIntValue],[runtimeTruth[@"installedHookCount"] unsignedIntValue],[runtimeTruth[@"enabledPatchCount"] unsignedIntValue],[runtimeTruth[@"originalPatchCount"] unsignedIntValue],[runtimeTruth[@"unknownPatchCount"] unsignedIntValue],[runtimeTruth[@"unreadablePatchCount"] unsignedIntValue]);'''
new='''HFALog("[V031314-TRUTH-SUMMARY] discovered=%u menu=%u startupOwned=%u startupApplied=%u installedMods=%u activeKnown=%u activeComplete=%u patchSites=%u hooks=%u installedHooks=%u enabled=%u original=%u unknown=%u unreadable=%u\\n",\n               [runtimeTruth[@"discoveredFeatureCount"] unsignedIntValue],[runtimeTruth[@"menuFeatureCount"] unsignedIntValue],[runtimeTruth[@"startupOwnedFeatureCount"] unsignedIntValue],[runtimeTruth[@"startupAppliedFeatureCount"] unsignedIntValue],[runtimeTruth[@"installedModificationCount"] unsignedIntValue],[runtimeTruth[@"activeFeatureCountKnown"] unsignedIntValue],[runtimeTruth[@"activeFeatureStateComplete"] boolValue]?1:0,[runtimeTruth[@"fixedPatchSiteCount"] unsignedIntValue],[runtimeTruth[@"runtimeHookCount"] unsignedIntValue],[runtimeTruth[@"installedHookCount"] unsignedIntValue],[runtimeTruth[@"enabledPatchCount"] unsignedIntValue],[runtimeTruth[@"originalPatchCount"] unsignedIntValue],[runtimeTruth[@"unknownPatchCount"] unsignedIntValue],[runtimeTruth[@"unreadablePatchCount"] unsignedIntValue]);\n        for(NSDictionary *h in [runtimeTruth[@"runtimeHooks"] isKindOfClass:NSArray.class]?runtimeTruth[@"runtimeHooks"]:@[]){NSDictionary *sem=[h[@"targetIL2CPP"] isKindOfClass:NSDictionary.class]?h[@"targetIL2CPP"]:@{};HFALog("[V031314-MOD-SEMANTIC] mechanism=runtime-hook backend=%s target=%s+%s resolved=%u canonical=%s\\n",[[h[@"backendId"] description] UTF8String]?:"?",[[h[@"targetImage"] description] UTF8String]?:"?",[[h[@"targetRVA"] description] UTF8String]?:"?",[sem[@"resolved"] boolValue]?1:0,[[sem[@"canonical"] description] UTF8String]?:"");}\n        for(NSDictionary *p in [runtimeTruth[@"patches"] isKindOfClass:NSArray.class]?runtimeTruth[@"patches"]:@[]){NSDictionary *sem=[p[@"targetIL2CPP"] isKindOfClass:NSDictionary.class]?p[@"targetIL2CPP"]:@{};HFALog("[V031314-MOD-SEMANTIC] mechanism=fixed-patch backend=%s target=%s+%s resolved=%u canonical=%s\\n",[[p[@"analyzerBackendId"] description] UTF8String]?:"?",[[p[@"targetImage"] description] UTF8String]?:"?",[[p[@"targetRVA"] description] UTF8String]?:"?",[sem[@"resolved"] boolValue]?1:0,[[sem[@"canonical"] description] UTF8String]?:"");}'''
if old not in t: raise SystemExit('bundle summary anchor missing')
t=t.replace(old,new,1)
t=t.replace('HFAMap_RuntimeModificationTruth_v031313.json','HFAMap_RuntimeModificationTruth_v031314.json')
t=t.replace('[V031313-TRUTH-FILE]','[V031314-TRUTH-FILE]')
TRACE.write_text(t)

u=UI.read_text()
u=u.replace('HFAMap RuntimeAnalyzer v0.3.13.13 RuntimeModificationTruthResolver','HFAMap RuntimeAnalyzer v0.3.13.14 ModificationSemanticResolver')
UI.write_text(u)

for token in ['HFATIL2CPPSemantic','[V031314-IL2CPP-TARGET]','discoveredFeatureCount','startupAppliedFeatureCount','installedModificationCount','activeFeatureStateComplete','effectiveFeatureCountDeprecated']:
    if token not in TRUTH.read_text(): raise SystemExit('v031314 truth token missing '+token)
for token in ['[V031314-TRUTH-SUMMARY]','[V031314-MOD-SEMANTIC]','HFAMap_RuntimeModificationTruth_v031314.json','[V031314-TRUTH-FILE]']:
    if token not in TRACE.read_text(): raise SystemExit('v031314 trace token missing '+token)
if 'v0.3.13.14 ModificationSemanticResolver' not in UI.read_text(): raise SystemExit('v031314 UI marker missing')
print('v0.3.13.14 modification semantic resolver applied')
