#import "ZPLegacyOffsetResolver.h"
#import "ZPAppIdentity.h"
#import <mach-o/dyld.h>
#import <mach-o/loader.h>
#import <mach/mach.h>
#import <objc/message.h>
#import <objc/runtime.h>
#include <dlfcn.h>
#include <ctype.h>
#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

typedef int (*ZPDecryptFn)(void *, void *);
static dispatch_queue_t ZPOffsetQueue(void){ static dispatch_queue_t q; static dispatch_once_t once; dispatch_once(&once,^{q=dispatch_queue_create("com.hfa.zpatchig.offset",DISPATCH_QUEUE_SERIAL);}); return q; }
static NSString *ZPDocs(void){ return [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory,NSUserDomainMask,YES) firstObject]; }
static NSString *ZPBase(const char *p){ if(!p)return @"?"; const char *s=strrchr(p,'/'); return [NSString stringWithUTF8String:s?s+1:p]?:@"?"; }
static NSString *ZPHex(const uint8_t *b,size_t n){ NSMutableString *s=[NSMutableString stringWithCapacity:n*2]; for(size_t i=0;i<n;i++)[s appendFormat:@"%02X",b[i]]; return s; }
static BOOL ZPRead(uintptr_t address,void *out,size_t size){ if(!address||!out||!size)return NO; vm_size_t copied=0; kern_return_t kr=vm_read_overwrite(mach_task_self(),(vm_address_t)address,(vm_size_t)size,(vm_address_t)out,&copied); return kr==KERN_SUCCESS&&copied==size; }
static void ZPWrite(NSDictionary *record){ if(!record||![NSJSONSerialization isValidJSONObject:record])return; NSData *d=[NSJSONSerialization dataWithJSONObject:record options:0 error:nil]; if(!d)return; NSMutableData *line=[d mutableCopy]; [line appendBytes:"\n" length:1]; NSString *path=[ZPDocs() stringByAppendingPathComponent:ZPLogFilename(@"OffsetEvents.jsonl")]; NSFileManager *fm=NSFileManager.defaultManager; if(![fm fileExistsAtPath:path])[fm createFileAtPath:path contents:nil attributes:nil]; NSFileHandle *h=[NSFileHandle fileHandleForWritingAtPath:path]; @try{[h seekToEndOfFile];[h writeData:line];[h closeFile];}@catch(__unused id e){} }
static BOOL ZPTextRangeForBase(const void *base,uintptr_t *startOut,uintptr_t *endOut){
    uint32_t count=_dyld_image_count(); for(uint32_t i=0;i<count;i++){ const struct mach_header *raw=_dyld_get_image_header(i); if((const void*)raw!=base||!raw||raw->magic!=MH_MAGIC_64)continue; intptr_t slide=_dyld_get_image_vmaddr_slide(i); const struct mach_header_64 *h=(const struct mach_header_64*)raw; const uint8_t *cur=(const uint8_t*)(h+1),*end=cur+h->sizeofcmds; for(uint32_t c=0;c<h->ncmds;c++){ if(cur+sizeof(struct load_command)>end)return NO; const struct load_command *lc=(const struct load_command*)cur; if(lc->cmdsize<sizeof(*lc)||cur+lc->cmdsize>end)return NO; if(lc->cmd==LC_SEGMENT_64){ const struct segment_command_64 *seg=(const struct segment_command_64*)cur; if(sizeof(*seg)+(uint64_t)seg->nsects*sizeof(struct section_64)>lc->cmdsize)return NO; const struct section_64 *sec=(const struct section_64*)(seg+1); for(uint32_t s=0;s<seg->nsects;s++)if(strncmp(sec[s].sectname,"__text",16)==0){ uintptr_t st=(uintptr_t)slide+(uintptr_t)sec[s].addr,en=st+(uintptr_t)sec[s].size; if(en>st&&sec[s].size<=64ULL*1024ULL*1024ULL){if(startOut)*startOut=st;if(endOut)*endOut=en;return YES;} } } cur+=lc->cmdsize; } } return NO;
}
static NSArray<NSNumber*> *ZPFindDecryptCandidates(uintptr_t start,uintptr_t end){
    NSMutableArray *out=[NSMutableArray array]; if(!start||end<=start)return out; const uint32_t a=0xD105C3FFu,b=0xB9400408u,c=0x53187D00u; for(uintptr_t p=start;p+0x44<=end;p+=4){ uint32_t x=0,y=0,z=0; memcpy(&x,(const void*)p,4); if(x!=a)continue; memcpy(&y,(const void*)(p+0x30),4); if(y!=b)continue; memcpy(&z,(const void*)(p+0x40),4); if(z!=c)continue; [out addObject:@(p)]; if(out.count>=16)break; } return out;
}
static BOOL ZPNumericASCII(const uint8_t *bytes,size_t len,unsigned long long *valueOut,NSString **textOut){ if(!bytes||!len||len>64)return NO; char tmp[65]={0}; size_t n=MIN(len,(size_t)64); memcpy(tmp,bytes,n); while(n&&isspace((unsigned char)tmp[n-1]))tmp[--n]=0; size_t i=0; while(i<n&&isspace((unsigned char)tmp[i]))i++; if(i>=n)return NO; for(size_t j=i;j<n;j++)if(tmp[j]&&(!isprint((unsigned char)tmp[j])))return NO; errno=0; char *end=NULL; unsigned long long v=strtoull(tmp+i,&end,0); if(errno||end==tmp+i)return NO; while(end&&*end&&isspace((unsigned char)*end))end++; if(end&&*end)return NO; if(valueOut)*valueOut=v; if(textOut)*textOut=[NSString stringWithUTF8String:tmp+i]; return YES; }
static BOOL ZPClassChainContains(id object,const char *needle){ for(Class c=object?object_getClass(object):Nil;c;c=class_getSuperclass(c)){ const char *n=class_getName(c); if(n&&strstr(n,needle))return YES; } return NO; }
static void ZPResolve(id wrapper,NSString *identifier,NSDictionary *feature,NSString *expectedImage){
    NSMutableDictionary *r=[@{@"schema":@"com.hfa.zpatchig.offset-event/v1",@"time":@(NSDate.date.timeIntervalSince1970),@"appIdentity":ZPAppIdentity(),@"identifier":identifier?:@"",@"expectedImage":expectedImage?:@"?",@"status":@"unresolved",@"confidence":@"none"} mutableCopy]; if(feature)r[@"feature"]=feature;
    if(!wrapper){r[@"reason"]=@"nil-wrapper";ZPWrite(r);return;} r[@"wrapperClass"]=NSStringFromClass(object_getClass(wrapper))?:@"?"; r[@"legacyWrapperClassMatch"]=@(ZPClassChainContains(wrapper,"IGSecretInt"));
    Method m=class_getInstanceMethod(object_getClass(wrapper),sel_registerName("secret")); if(!m||method_getNumberOfArguments(m)!=2){r[@"reason"]=@"secret-getter-missing";ZPWrite(r);return;} const char *enc=method_getTypeEncoding(m); if(enc)r[@"secretGetterEncoding"]=[NSString stringWithUTF8String:enc]; IMP getter=method_getImplementation(m); Dl_info info={0}; if(!getter||!dladdr((void*)getter,&info)||!info.dli_fbase||!info.dli_fname){r[@"reason"]=@"secret-getter-owner-unresolved";ZPWrite(r);return;}
    NSString *image=ZPBase(info.dli_fname); r[@"getterImage"]=image; r[@"getterRVA"]=[NSString stringWithFormat:@"0x%llX",(unsigned long long)((uintptr_t)getter-(uintptr_t)info.dli_fbase)]; if(expectedImage.length&&![image isEqualToString:expectedImage]){r[@"reason"]=@"getter-image-mismatch";ZPWrite(r);return;}
    uintptr_t ts=0,te=0; if(!ZPTextRangeForBase(info.dli_fbase,&ts,&te)){r[@"reason"]=@"text-range-unresolved";ZPWrite(r);return;} NSArray<NSNumber*> *candidates=ZPFindDecryptCandidates(ts,te); r[@"decryptFingerprintMatches"]=@(candidates.count); if(candidates.count!=1){r[@"reason"]=candidates.count?@"decrypt-fingerprint-ambiguous":@"decrypt-fingerprint-not-found";ZPWrite(r);return;} uintptr_t decrypt=candidates.firstObject.unsignedLongLongValue; r[@"decryptRVA"]=[NSString stringWithFormat:@"0x%llX",(unsigned long long)(decrypt-(uintptr_t)info.dli_fbase)];
    char *ret=method_copyReturnType(m); char rc=ret?ret[0]:'?'; free(ret); if(!(rc=='^'||rc=='@'||rc=='*')){r[@"reason"]=[NSString stringWithFormat:@"unsupported-secret-return-%c",rc];ZPWrite(r);return;} void *secret=NULL; @try{ secret=((void*(*)(id,SEL))objc_msgSend)(wrapper,sel_registerName("secret")); }@catch(__unused id e){secret=NULL;} if(!secret){r[@"reason"]=@"secret-null";ZPWrite(r);return;}
    uint32_t header[2]={0}; if(!ZPRead((uintptr_t)secret,header,sizeof(header))){r[@"reason"]=@"secret-header-unreadable";ZPWrite(r);return;} uint32_t len=header[0],flags=header[1]; r[@"secretLength"]=@(len); r[@"secretFlags"]=[NSString stringWithFormat:@"0x%08X",flags]; size_t blobSize=(size_t)(len&~0xFu)+0x28u; if(blobSize<=0x28u)blobSize=0x28u; if(!len||len>0x10000u||blobSize>0x11000u){r[@"reason"]=@"secret-length-out-of-range";ZPWrite(r);return;}
    void *copy=malloc(blobSize); uint8_t *plain=(uint8_t*)calloc(1,(size_t)len+0x20u); if(!copy||!plain){free(copy);free(plain);r[@"reason"]=@"allocation-failed";ZPWrite(r);return;} if(!ZPRead((uintptr_t)secret,copy,blobSize)){free(copy);free(plain);r[@"reason"]=@"secret-blob-unreadable";ZPWrite(r);return;} int result=((ZPDecryptFn)decrypt)(copy,plain); r[@"decryptResult"]=@(result); if(result==0){ size_t show=MIN((size_t)len,(size_t)32); r[@"plaintextPrefixHex"]=ZPHex(plain,show); unsigned long long value=0; NSString *text=nil; if(ZPNumericASCII(plain,len,&value,&text)){r[@"status"]=@"validated";r[@"confidence"]=@"high";r[@"offset"]=[NSString stringWithFormat:@"0x%llX",value];r[@"plaintext"] = text?:@"";r[@"reason"]=@"unique-current-image-fingerprint-plus-numeric-plaintext";} else if(len==4||len==8){ uint64_t raw=0; memcpy(&raw,plain,MIN((size_t)len,sizeof(raw))); r[@"status"]=@"inferred";r[@"confidence"]=@"medium";r[@"binaryOffsetCandidate"]=[NSString stringWithFormat:@"0x%llX",(unsigned long long)raw];r[@"reason"]=@"unique-fingerprint-but-binary-plaintext-needs-cross-check";} else r[@"reason"]=@"decrypt-succeeded-non-numeric-plaintext"; } else r[@"reason"]=@"decrypt-call-failed"; free(copy);free(plain);ZPWrite(r);
}
void ZPLegacyOffsetResolverSchedule(id wrapper,NSString *identifier,NSDictionary *feature,NSString *expectedImage){ if(!wrapper||!identifier.length)return; id retained=wrapper; NSString *iid=[identifier copy],*img=[expectedImage copy]; NSDictionary *f=[feature copy]; dispatch_async(ZPOffsetQueue(),^{@autoreleasepool{ZPResolve(retained,iid,f,img);}}); }
