from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
src = ROOT / "src/HFAMapSenderDerivedProvenanceResolver.mm"
out = ROOT / "src/HFAMapSenderDerivedProvenanceResolver2517.mm"
text = src.read_text()

old_key = '''NSString *key=[NSString stringWithFormat:@"%llx:%u:%u:%u",(unsigned long long)pc,(unsigned)regs[0].root,(unsigned)regs[1].root,(unsigned)regs[2].root];'''
new_key = '''NSString *key=[NSString stringWithFormat:@"%llx:%u:%u:%u:%u:%u:%u:%u:%u:%u:%lld:%lld",(unsigned long long)pc,(unsigned)regs[0].root,(unsigned)regs[1].root,(unsigned)regs[2].root,(unsigned)regs[8].root,(unsigned)regs[19].root,(unsigned)regs[20].root,(unsigned)regs[21].root,(unsigned)regs[19].kind,(unsigned)regs[20].kind,(long long)regs[19].fieldOffset,(long long)regs[20].fieldOffset];'''
if old_key not in text:
    raise SystemExit("v2517: enqueue-key anchor missing")
text = text.replace(old_key, new_key, 1)

old_ldr = '''if((insn&0xffc00000U)==0xf9400000U){unsigned rt=insn&31U,rn=(insn>>5)&31U;uint64_t imm=((insn>>10)&0xfffU)<<3;if(rt<31&&rn<31&&HFASDHasValue(regs[rn])){uint64_t v=0;if(HFASDRead64(regs[rn].value+imm,&v)){HFASDReg n=HFASDConcrete(HFASDFieldLoad,v,rva);n.root=regs[rn].root;n.confidence=n.root?HFASDConfidenceDerived:HFASDConfidenceNone;n.originRVA=regs[rn].originRVA;n.fieldOffset=regs[rn].fieldOffset+(int64_t)imm;regs[rt]=n;}}return YES;}'''
new_ldr = '''if((insn&0xffc00000U)==0xf9400000U){unsigned rt=insn&31U,rn=(insn>>5)&31U;uint64_t imm=((insn>>10)&0xfffU)<<3;if(rt<31&&rn==31){NSData *saved=stack[@((int64_t)imm)];if(saved.length==sizeof(HFASDReg)){HFASDReg n={};memcpy(&n,saved.bytes,sizeof(n));n.sourceRVA=rva;regs[rt]=n;}}else if(rt<31&&rn<31&&HFASDHasValue(regs[rn])){uint64_t v=0;if(HFASDRead64(regs[rn].value+imm,&v)){HFASDReg n=HFASDConcrete(HFASDFieldLoad,v,rva);n.root=regs[rn].root;n.confidence=n.root?HFASDConfidenceDerived:HFASDConfidenceNone;n.originRVA=regs[rn].originRVA;n.fieldOffset=regs[rn].fieldOffset+(int64_t)imm;regs[rt]=n;}}return YES;}'''
if old_ldr not in text:
    raise SystemExit("v2517: ldr anchor missing")
text = text.replace(old_ldr, new_ldr, 1)

old_dead = '''if((insn&0xffc00000U)==0xf9400000U){return YES;}'''
if old_dead not in text:
    raise SystemExit("v2517: dead stack reload anchor missing")
text = text.replace(old_dead, '''/* v2.5.17: stack reload handled by the unified LDR branch above. */''', 1)

text = text.replace('@"2.5.16-dev"', '@"2.5.17-dev"')
text = text.replace('@"2.5.16-dev-sender-derived-provenance"', '@"2.5.17-dev-sender-field-callresult"')
text = text.replace('@"READ-ONLY-SENDER-FIELD-CALL-BRANCH-PROVENANCE"', '@"READ-ONLY-SENDER-FIELD-STACK-CALLRESULT-BRANCH-PROVENANCE"')

banner = '// GENERATED BY tools/generate_v2517_sender_resolver.py — do not edit directly.\n'
out.write_text(banner + text)
print(out)
