from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"

# Exact method-pointer index: the old deadline was only checked per class. Add a
# check inside the method loop so one pathological class cannot turn a 750 ms
# budget into minutes.
method = (SRC / "HFAIL2CPPMethodIndex.mm").read_text()
needle = '''            for (NSUInteger mi = 0; mi < kHFAMaxMethodsPerClass && methodsInspected < kHFAMaxMethods; ++mi) {\n                const void *method = classMethods(klass, &iter);'''
replacement = '''            for (NSUInteger mi = 0; mi < kHFAMaxMethodsPerClass && methodsInspected < kHFAMaxMethods; ++mi) {\n                if (NSDate.date.timeIntervalSince1970 > deadline) { timedOut = YES; break; }\n                const void *method = classMethods(klass, &iter);'''
if needle not in method:
    raise SystemExit("v2.5.21 method-index inner-loop anchor missing")
method = method.replace(needle, replacement, 1)
(SRC / "HFAIL2CPPMethodIndex2521.mm").write_text("// GENERATED BY tools/generate_v2521_il2cpp_deadline.py — do not edit directly.\n" + method)

# Containing-method range index: same hardening for its 900 ms budget.
ranges = (SRC / "HFAIL2CPPMethodRangeIndex.mm").read_text()
needle = '''                for (NSUInteger mi = 0; mi < kHFARangeMaxMethodsPerClass && methodsInspected < kHFARangeMaxMethods; ++mi) {\n                    const void *method = classMethods(klass, &iter);'''
replacement = '''                for (NSUInteger mi = 0; mi < kHFARangeMaxMethodsPerClass && methodsInspected < kHFARangeMaxMethods; ++mi) {\n                    if (NSDate.date.timeIntervalSince1970 > deadline) { timedOut = YES; break; }\n                    const void *method = classMethods(klass, &iter);'''
if needle not in ranges:
    raise SystemExit("v2.5.21 range-index inner-loop anchor missing")
ranges = ranges.replace(needle, replacement, 1)
(SRC / "HFAIL2CPPMethodRangeIndex2521.mm").write_text("// GENERATED BY tools/generate_v2521_il2cpp_deadline.py — do not edit directly.\n" + ranges)

print(SRC / "HFAIL2CPPMethodIndex2521.mm")
print(SRC / "HFAIL2CPPMethodRangeIndex2521.mm")
