from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"

# Loaded-dylib scanner integration.
scanner = (SRC / "HFAMapBundleRootScanner.mm").read_text()
scanner = scanner.replace(
    '#import "HFAMapLoadedMenuFeatureEnumerator.h"\n',
    '#import "HFAMapLoadedMenuFeatureEnumerator.h"\n#import "HFAMapMenuImplementationInventory.h"\n',
    1,
)
anchor = '''        NSError *secretError=nil; NSDictionary *secretEvidence = directed ? HFAMapResolveSecretWrapperEvidence(path,directed,&secretError) : nil;\n        NSError *secretPersistError=nil; BOOL secretSaved = secretEvidence && HFAMapPersistSecretWrapperEvidence(secretEvidence,&secretPersistError);\n        NSError *finalError=evidenceError?:evidencePersistError?:loadedError?:loadedPersistError?:rootGraphError?:rootGraphPersistError?:directedError?:directedPersistError?:inventoryError?:inventoryPersistError?:secretError?:secretPersistError?:catalogError?:catalogPersistError;'''
replacement = '''        NSError *secretError=nil; NSDictionary *secretEvidence = directed ? HFAMapResolveSecretWrapperEvidence(path,directed,&secretError) : nil;\n        NSError *secretPersistError=nil; BOOL secretSaved = secretEvidence && HFAMapPersistSecretWrapperEvidence(secretEvidence,&secretPersistError);\n        NSError *implementationError=nil;\n        NSDictionary *implementationInventory = featureInventory ? HFAMapBuildMenuImplementationInventory(path, featureInventory, directed?:@{}, secretEvidence?:@{}, @[], &implementationError) : nil;\n        NSError *implementationPersistError=nil;\n        BOOL implementationSaved = implementationInventory && HFAMapPersistMenuImplementationInventory(implementationInventory,&implementationPersistError);\n        NSError *finalError=evidenceError?:evidencePersistError?:loadedError?:loadedPersistError?:rootGraphError?:rootGraphPersistError?:directedError?:directedPersistError?:inventoryError?:inventoryPersistError?:secretError?:secretPersistError?:implementationError?:implementationPersistError?:catalogError?:catalogPersistError;'''
if anchor not in scanner:
    raise SystemExit("v2520 scanner integration anchor missing")
scanner = scanner.replace(anchor, replacement, 1)
log_anchor = '''            @"secretWrapperEvidence":@(secretEvidence!=nil), @"secretWrapperEvidenceSaved":@(secretSaved), @"secretWrapperEvidenceCount":secretEvidence[@"wrapperEvidenceCount"]?:@0 });'''
log_replacement = '''            @"secretWrapperEvidence":@(secretEvidence!=nil), @"secretWrapperEvidenceSaved":@(secretSaved), @"secretWrapperEvidenceCount":secretEvidence[@"wrapperEvidenceCount"]?:@0,\n            @"menuImplementationInventory":@(implementationInventory!=nil), @"menuImplementationInventorySaved":@(implementationSaved),\n            @"menuImplementationFeatureCount":implementationInventory[@"summary"][@"featureCount"]?:@0,\n            @"menuImplementationRuntimeMethodCount":implementationInventory[@"summary"][@"runtimeMethodCount"]?:@0,\n            @"menuImplementationPatchCount":implementationInventory[@"summary"][@"memoryPatchCount"]?:@0,\n            @"menuImplementationStateMutationCandidateCount":implementationInventory[@"summary"][@"stateMutationCandidateCount"]?:@0 });'''
if log_anchor not in scanner:
    raise SystemExit("v2520 scanner log anchor missing")
scanner = scanner.replace(log_anchor, log_replacement, 1)
(SRC / "HFAMapBundleRootScanner2520.mm").write_text("// GENERATED BY tools/generate_v2520_integration.py — do not edit directly.\n" + scanner)

# App-name scoped static-catalog output. This also prevents multi-game archives
# from containing anonymous HFAMap/Catalogs directories.
catalog = (SRC / "HFAMapStaticCatalog.mm").read_text()
catalog = catalog.replace(
    '#import "HFAMapStaticCatalog.h"\n',
    '#import "HFAMapStaticCatalog.h"\n#import "HFAMapOutputName.h"\n',
    1,
)
old_dir = 'return [[documents stringByAppendingPathComponent:@"HFAMap"] stringByAppendingPathComponent:@"Catalogs"];'
new_dir = 'return [[documents stringByAppendingPathComponent:[NSString stringWithFormat:@"%@_HFAMap", HFAHostAppName()]] stringByAppendingPathComponent:@"Catalogs"];'
if old_dir not in catalog:
    raise SystemExit("v2520 catalog directory anchor missing")
catalog = catalog.replace(old_dir, new_dir, 1)
old_path = 'NSString *path = [directory stringByAppendingPathComponent:[key stringByAppendingPathExtension:@"json"]];'
new_path = 'NSString *fileName = [NSString stringWithFormat:@"%@_HFAMap_StaticCatalog_%@.json", HFAHostAppName(), key];\n    NSString *path = [directory stringByAppendingPathComponent:fileName];'
if old_path not in catalog:
    raise SystemExit("v2520 catalog filename anchor missing")
catalog = catalog.replace(old_path, new_path, 1)
(SRC / "HFAMapStaticCatalog2520.mm").write_text("// GENERATED BY tools/generate_v2520_integration.py — do not edit directly.\n" + catalog)

print(SRC / "HFAMapBundleRootScanner2520.mm")
print(SRC / "HFAMapStaticCatalog2520.mm")
