from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"

entry = (SRC / "HFAMapEntry.mm").read_text()
entry = entry.replace('#import "HFAMapStaticCatalog.h"\n', '#import "HFAMapStaticCatalog.h"\n#import "HFAMapBuildInfo.h"\n', 1)
entry = entry.replace('title.text = @"HFAMap v2.5.7-dev";', 'title.text = HFAMapDisplayVersion();', 1)
entry = entry.replace('NSLog(@"[HFAMap] v2.5.7 UI installed on window=%@", window);', 'NSLog(@"[HFAMap] %@ UI installed on window=%@", HFAMapBuildVersion(), window);', 1)
entry = entry.replace('NSLog(@"[HFAMap] v2.5.7 Theos build entry loaded");', 'NSLog(@"[HFAMap] %@ Theos build entry loaded", HFAMapBuildVersion());', 1)
(SRC / "HFAMapEntry25201.mm").write_text("// GENERATED BY tools/generate_v25201_build_identity.py — do not edit directly.\n" + entry)

diag = (SRC / "HFAMapDiagnostics.mm").read_text()
diag = diag.replace('#import "HFAMapOutputName.h"\n', '#import "HFAMapOutputName.h"\n#import "HFAMapBuildInfo.h"\n', 1)
diag = diag.replace('@"version": @"2.5.8-dev-universal-imported-dylib-evidence",\n        @"policy": @"UNIVERSAL-ONLY",', '@"version": HFAMapBuildVersion(),\n        @"buildVersion": HFAMapBuildVersion(),\n        @"componentVersion": HFAMapBuildComponent(),\n        @"policy": HFAMapBuildPolicy(),', 1)
(SRC / "HFAMapDiagnostics25201.mm").write_text("// GENERATED BY tools/generate_v25201_build_identity.py — do not edit directly.\n" + diag)

print(SRC / "HFAMapEntry25201.mm")
print(SRC / "HFAMapDiagnostics25201.mm")
