from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"

base = (SRC / "HFAMapBundleRootScanner2520.mm").read_text()

# v2.5.21 keeps the fast, already-proven feature inventory path on the UI critical
# path, but moves expensive implementation enrichment off that path. The full
# Runtime Method / Patch / State-Mutation inventory is still produced and saved.
old = '''        NSError *implementationError=nil;\n        NSDictionary *implementationInventory = featureInventory ? HFAMapBuildMenuImplementationInventory(path, featureInventory, directed?:@{}, secretEvidence?:@{}, @[], &implementationError) : nil;\n        NSError *implementationPersistError=nil;\n        BOOL implementationSaved = implementationInventory && HFAMapPersistMenuImplementationInventory(implementationInventory,&implementationPersistError);\n        NSError *finalError=evidenceError?:evidencePersistError?:loadedError?:loadedPersistError?:rootGraphError?:rootGraphPersistError?:directedError?:directedPersistError?:inventoryError?:inventoryPersistError?:secretError?:secretPersistError?:implementationError?:implementationPersistError?:catalogError?:catalogPersistError;'''
new = '''        NSError *finalError=evidenceError?:evidencePersistError?:loadedError?:loadedPersistError?:rootGraphError?:rootGraphPersistError?:directedError?:directedPersistError?:inventoryError?:inventoryPersistError?:secretError?:secretPersistError?:catalogError?:catalogPersistError;\n        if (featureInventory) {\n            NSDictionary *featureSnapshot = [featureInventory retain];\n            NSDictionary *directedSnapshot = [directed ?: @{} retain];\n            NSDictionary *secretSnapshot = [secretEvidence ?: @{} retain];\n            NSString *pathSnapshot = [path copy];\n            HFADiagnosticsLog(@"menu-implementation-enrichment", @"scheduled", @{\n                @"featureCount": @([featureInventory[@"featureCandidates"] count]),\n                @"uiBlocking": @NO,\n                @"policy": @"ASYNC-POST-UI-FEATURE-IMPLEMENTATION-ENRICHMENT"\n            });\n            dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY, 0), ^{\n                @autoreleasepool {\n                    NSError *implementationError=nil;\n                    NSDictionary *implementationInventory = HFAMapBuildMenuImplementationInventory(pathSnapshot, featureSnapshot, directedSnapshot, secretSnapshot, @[], &implementationError);\n                    NSError *implementationPersistError=nil;\n                    BOOL implementationSaved = implementationInventory && HFAMapPersistMenuImplementationInventory(implementationInventory,&implementationPersistError);\n                    HFADiagnosticsLog(@"menu-implementation-enrichment", implementationSaved ? @"complete" : @"failed", @{\n                        @"saved": @(implementationSaved),\n                        @"featureCount": implementationInventory[@"summary"][@"featureCount"] ?: @0,\n                        @"runtimeMethodCount": implementationInventory[@"summary"][@"runtimeMethodCount"] ?: @0,\n                        @"memoryPatchCount": implementationInventory[@"summary"][@"memoryPatchCount"] ?: @0,\n                        @"stateMutationCandidateCount": implementationInventory[@"summary"][@"stateMutationCandidateCount"] ?: @0,\n                        @"analysisTruncated": implementationInventory[@"summary"][@"analysisTruncated"] ?: @NO,\n                        @"error": (implementationError ?: implementationPersistError).localizedDescription ?: @""\n                    });\n                    [featureSnapshot release];\n                    [directedSnapshot release];\n                    [secretSnapshot release];\n                    [pathSnapshot release];\n                }\n            });\n        }'''
if old not in base:
    raise SystemExit("v2.5.21 implementation-enrichment anchor missing")
base = base.replace(old, new, 1)

old_log = '''            @"secretWrapperEvidence":@(secretEvidence!=nil), @"secretWrapperEvidenceSaved":@(secretSaved), @"secretWrapperEvidenceCount":secretEvidence[@"wrapperEvidenceCount"]?:@0,\n            @"menuImplementationInventory":@(implementationInventory!=nil), @"menuImplementationInventorySaved":@(implementationSaved),\n            @"menuImplementationFeatureCount":implementationInventory[@"summary"][@"featureCount"]?:@0,\n            @"menuImplementationRuntimeMethodCount":implementationInventory[@"summary"][@"runtimeMethodCount"]?:@0,\n            @"menuImplementationPatchCount":implementationInventory[@"summary"][@"memoryPatchCount"]?:@0,\n            @"menuImplementationStateMutationCandidateCount":implementationInventory[@"summary"][@"stateMutationCandidateCount"]?:@0 });'''
new_log = '''            @"secretWrapperEvidence":@(secretEvidence!=nil), @"secretWrapperEvidenceSaved":@(secretSaved), @"secretWrapperEvidenceCount":secretEvidence[@"wrapperEvidenceCount"]?:@0,\n            @"menuImplementationEnrichmentScheduled":@(featureInventory!=nil),\n            @"menuImplementationEnrichmentUiBlocking":@NO });'''
if old_log not in base:
    raise SystemExit("v2.5.21 ui-ready log anchor missing")
base = base.replace(old_log, new_log, 1)

(SRC / "HFAMapBundleRootScanner2521.mm").write_text("// GENERATED BY tools/generate_v2521_async_enrichment.py — do not edit directly.\n" + base)
print(SRC / "HFAMapBundleRootScanner2521.mm")
