from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
src = ROOT / "src/HFAMapLoadedDylibEvidenceResolver.mm"
out = ROOT / "src/HFAMapLoadedDylibEvidenceResolver2519.mm"
text = src.read_text()

start = text.index('            uint64_t firstWord = 0;\n            if (HFAReadMemory(value, &firstWord, sizeof(firstWord))) {\n                Class cls = object_getClass((id)(uintptr_t)value);')
end_marker = '\n\n            NSString *cstring = HFAReadableCString(value);'
end = text.index(end_marker, start)
replacement = '''            // v2.5.19 stability: do not treat arbitrary readable data pointers as ObjC objects.\n            // Runtime instance recovery from global data is disabled unless a future path can\n            // validate the isa without invoking ObjC runtime on an untrusted candidate.\n            BOOL objcInstanceCandidateSkipped = YES;\n            (void)objcInstanceCandidateSkipped;'''
text = text[:start] + replacement + text[end:]
text = text.replace('@"runtimeStateTruncated": @(truncated)',
                    '@"objcInstanceCandidatePolicy": @"DISABLED-UNTRUSTED-GLOBAL-POINTER-FAIL-CLOSED",\n        @"runtimeStateTruncated": @(truncated)', 1)
out.write_text('// GENERATED BY tools/generate_v2519_loaded_safe.py — do not edit directly.\n' + text)
print(out)
