from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
subprocess.run([sys.executable, str(ROOT / "tools/generate_v2518_helper_summary.py")], check=True)
src = ROOT / "src/HFAMapSenderDerivedProvenanceResolver2518.mm"
out = ROOT / "src/HFAMapSenderDerivedProvenanceResolver2519.mm"
text = src.read_text()

old = 'static BOOL HFASDSenderDerived(HFASDReg r) { return r.root == HFASDRootSender; }'
new = 'static BOOL HFASDSenderDerived(HFASDReg r) { return r.root == HFASDRootSender && r.confidence != HFASDConfidenceCandidate; }'
if old not in text:
    raise SystemExit('v2519: sender confidence anchor missing')
text = text.replace(old, new, 1)

old_conf = 'n.confidence=n.root?HFASDConfidenceDerived:HFASDConfidenceNone;'
new_conf = 'n.confidence=(regs[rn].confidence==HFASDConfidenceCandidate)?HFASDConfidenceCandidate:(n.root?HFASDConfidenceDerived:HFASDConfidenceNone);'
if text.count(old_conf) < 4:
    raise SystemExit('v2519: field confidence anchors missing')
text = text.replace(old_conf, new_conf)

old_enqueue = 'HFASDEnqueue(queue,scheduled,t,depth+1,regs,stack,cond,info.dli_fbase);HFASDReg ret=HFASDCallResultFromArgs(regs,rva);'
if old_enqueue not in text:
    raise SystemExit('v2519: helper enqueue anchor missing')
text = text.replace(old_enqueue, 'HFASDReg ret=HFASDCallResultFromArgs(regs,rva);', 1)

old_result = '@"branchCount":@(branches.count),@"branches":branches,@"senderDerivedBranchCount":@(senderBranches.count),@"senderDerivedBranches":senderBranches,@"helperSummaryCount":@(helperSummaries.count)'
new_result = '@"branchCount":@(branches.count),@"branches":branches,@"senderDerivedBranchCount":@(senderBranches.count),@"senderDerivedBranches":senderBranches,@"analysisTruncated":@(decoded>=kHFASDMaxInstructions || blocks.count>=kHFASDMaxBlocks || calls.count>=kHFASDMaxCalls || branches.count>=kHFASDMaxBranches),@"provenanceConfidence":(decoded>=kHFASDMaxInstructions || blocks.count>=kHFASDMaxBlocks || calls.count>=kHFASDMaxCalls || branches.count>=kHFASDMaxBranches)?@"incomplete":@"bounded-complete",@"helperSummaryCount":@(helperSummaries.count)'
if old_result not in text:
    raise SystemExit('v2519: result truncation anchor missing')
text = text.replace(old_result, new_result, 1)

text = text.replace('@"2.5.18-dev"', '@"2.5.19-dev"')
text = text.replace('@"2.5.18-dev-interprocedural-helper-summary"', '@"2.5.19-dev-stability-verified-helper-return"')
text = text.replace('@"READ-ONLY-INTERPROCEDURAL-HELPER-RETURN-PROVENANCE"', '@"READ-ONLY-FAIL-CLOSED-VERIFIED-HELPER-RETURN-PROVENANCE"')
out.write_text('// GENERATED BY tools/generate_v2519_sender_safe.py — do not edit directly.\n' + text)
print(out)
